BEGIN;
TRUNCATE folders, notes RESTART IDENTITY CASCADE;

insert into folders (id, folder_name) values (1, 'Alfy');
insert into folders (id, folder_name) values (2, 'Gertrud');
insert into folders (id, folder_name) values (3, 'Mohammed');
insert into folders (id, folder_name) values (4, 'Vivianna');
insert into folders (id, folder_name) values (5, 'Virgilio');
insert into folders (id, folder_name) values (6, 'Gayle');
insert into folders (id, folder_name) values (7, 'Gigi');
insert into folders (id, folder_name) values (8, 'Omero');
insert into folders (id, folder_name) values (9, 'Raimund');
insert into folders (id, folder_name) values (10, 'Bryanty');
insert into folders (id, folder_name) values (11, 'Donielle');
insert into folders (id, folder_name) values (12, 'Asia');
insert into folders (id, folder_name) values (13, 'Beatrisa');
insert into folders (id, folder_name) values (14, 'Yolane');
insert into folders (id, folder_name) values (15, 'Gayler');
insert into folders (id, folder_name) values (16, 'Arly');
insert into folders (id, folder_name) values (17, 'Gerty');

insert into notes (id, note_name, content, date_created, folder_id) values (1, 'Johna', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2018-09-28 20:20:52', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (2, 'Oralee', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2018-12-07 15:15:10', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (3, 'Davita', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', '2018-10-17 03:05:18', 3);
insert into notes (id, note_name, content, date_created, folder_id) values (4, 'Melodee', 'Nam nulla.', '2019-04-11 13:13:33', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (5, 'Gaspard', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2018-10-29 09:49:24', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (6, 'Husein', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '2018-11-30 03:01:58', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (7, 'Bliss', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2019-04-19 07:36:03', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (8, 'Samuele', 'Curabitur in libero ut massa volutpat convallis.', '2019-02-21 14:26:23', 3);
insert into notes (id, note_name, content, date_created, folder_id) values (9, 'Hillier', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2018-12-15 21:34:03', 12);
insert into notes (id, note_name, content, date_created, folder_id) values (10, 'Olwen', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2018-06-07 18:22:50', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (11, 'Eliot', 'Aliquam non mauris. Morbi non lectus.', '2019-01-20 11:14:59', 12);
insert into notes (id, note_name, content, date_created, folder_id) values (12, 'Jessy', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2018-04-30 01:11:43', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (13, 'Godart', 'Vivamus vel nulla eget eros elementum pellentesque.', '2018-08-08 20:40:36', 12);
insert into notes (id, note_name, content, date_created, folder_id) values (14, 'Bobby', 'Integer ac leo. Pellentesque ultrices mattis odio.', '2018-09-21 12:30:58', 9);
insert into notes (id, note_name, content, date_created, folder_id) values (15, 'Antonetta', 'Morbi vel lectus in quam fringilla rhoncus.', '2019-01-20 17:42:52', 10);
insert into notes (id, note_name, content, date_created, folder_id) values (16, 'Charis', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2018-11-10 04:51:42', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (17, 'Marcelline', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2018-10-19 22:14:34', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (18, 'Hebert', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-12-09 19:17:53', 7);
insert into notes (id, note_name, content, date_created, folder_id) values (19, 'Siegfried', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '2018-09-16 15:05:58', 11);
insert into notes (id, note_name, content, date_created, folder_id) values (20, 'Pippa', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2019-04-24 11:20:06', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (21, 'Harlene', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2018-06-04 03:11:43', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (22, 'Mick', 'Quisque ut erat. Curabitur gravida nisi at nibh.', '2018-07-12 09:29:39', 7);
insert into notes (id, note_name, content, date_created, folder_id) values (23, 'Gregoor', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2019-05-09 13:25:57', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (24, 'Debora', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', '2018-07-28 09:10:08', 10);
insert into notes (id, note_name, content, date_created, folder_id) values (25, 'Renie', 'In hac habitasse platea dictumst.', '2019-03-09 08:21:24', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (26, 'Pietrek', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', '2019-02-19 18:48:01', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (27, 'Ewen', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2019-03-16 18:43:51', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (28, 'Brady', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', '2018-11-03 15:34:54', 7);
insert into notes (id, note_name, content, date_created, folder_id) values (29, 'Lotta', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '2019-01-13 11:16:25', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (30, 'Charlena', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2018-12-15 07:39:24', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (31, 'Vittorio', 'Pellentesque ultrices mattis odio.', '2018-11-20 03:09:14', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (32, 'Way', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', '2018-05-19 18:02:47', 9);
insert into notes (id, note_name, content, date_created, folder_id) values (33, 'Lancelot', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '2018-05-30 10:03:39', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (34, 'Ava', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2019-04-05 01:25:20', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (35, 'Tremayne', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', '2018-11-07 09:53:57', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (36, 'Jackqueline', 'Vivamus vestibulum sagittis sapien.', '2019-03-24 01:28:38', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (37, 'Malachi', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '2018-07-29 17:13:19', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (38, 'Pascal', 'Morbi ut odio.', '2018-08-02 22:31:58', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (39, 'Xavier', 'Integer a nibh. In quis justo.', '2018-10-24 04:04:13', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (40, 'Thaxter', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2018-03-30 11:58:13', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (41, 'Timoteo', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2018-09-06 08:40:45', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (42, 'Dorian', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2018-04-07 15:02:16', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (43, 'Laraine', 'Nulla nisl.', '2018-08-06 17:50:31', 10);
insert into notes (id, note_name, content, date_created, folder_id) values (44, 'Grannie', 'Cras non velit nec nisi vulputate nonummy.', '2018-09-23 01:35:11', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (45, 'Dollie', 'Integer ac neque. Duis bibendum.', '2018-06-20 14:41:11', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (46, 'Lonnie', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2018-06-22 16:11:35', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (47, 'Kevyn', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', '2018-05-26 09:01:56', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (48, 'Kaile', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-12-18 02:54:06', 11);
insert into notes (id, note_name, content, date_created, folder_id) values (49, 'Torre', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2018-08-16 00:27:13', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (50, 'Ashia', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', '2019-02-21 20:54:13', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (51, 'Harriot', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2019-03-22 02:25:20', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (52, 'Dotti', 'Maecenas tincidunt lacus at velit.', '2018-05-20 07:35:31', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (53, 'Ruthi', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', '2018-09-08 00:44:00', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (54, 'Lennard', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '2019-03-06 06:26:52', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (55, 'Randee', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '2018-09-17 04:11:59', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (56, 'Vale', 'Maecenas rhoncus aliquam lacus.', '2018-05-19 15:33:08', 10);
insert into notes (id, note_name, content, date_created, folder_id) values (57, 'Melody', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', '2018-10-22 05:42:20', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (58, 'Martelle', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2018-10-30 16:47:05', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (59, 'Mariele', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2019-03-13 22:32:25', 4);
insert into notes (id, note_name, content, date_created, folder_id) values (60, 'Tory', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2019-01-17 04:30:11', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (61, 'Viviyan', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-12-21 14:32:19', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (62, 'Lorenza', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', '2019-03-18 22:02:32', 12);
insert into notes (id, note_name, content, date_created, folder_id) values (63, 'Dallis', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2018-06-17 17:26:18', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (64, 'Roby', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2019-05-06 02:32:53', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (65, 'Rosina', 'Pellentesque at nulla.', '2018-11-04 13:43:26', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (66, 'Merilee', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2018-12-09 18:39:30', 11);
insert into notes (id, note_name, content, date_created, folder_id) values (67, 'Anthony', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2019-02-21 07:05:19', 9);
insert into notes (id, note_name, content, date_created, folder_id) values (68, 'Alfredo', 'Nunc rhoncus dui vel sem. Sed sagittis.', '2019-03-11 07:37:48', 2);
insert into notes (id, note_name, content, date_created, folder_id) values (69, 'Jillayne', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', '2019-04-04 00:30:29', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (70, 'Tad', 'Etiam pretium iaculis justo.', '2018-05-25 10:09:22', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (71, 'Jemmie', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', '2019-01-06 14:18:10', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (72, 'Bastian', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', '2018-11-21 13:04:56', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (73, 'Maegan', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2019-04-10 03:21:37', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (74, 'Linoel', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-04-06 10:52:30', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (75, 'Elberta', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2018-07-02 21:24:26', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (76, 'Nolie', 'In sagittis dui vel nisl.', '2019-04-17 11:49:54', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (77, 'Kelsi', 'Morbi a ipsum.', '2018-05-21 05:23:01', 12);
insert into notes (id, note_name, content, date_created, folder_id) values (78, 'Miltie', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2018-07-03 05:44:17', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (79, 'Merla', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', '2018-11-23 10:31:31', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (80, 'Arch', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', '2019-03-11 01:50:24', 14);
insert into notes (id, note_name, content, date_created, folder_id) values (81, 'Bernice', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', '2018-04-13 10:00:29', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (82, 'Beverlie', 'Sed ante.', '2019-03-20 17:02:16', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (83, 'Sheree', 'Duis mattis egestas metus. Aenean fermentum.', '2018-08-12 09:33:25', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (84, 'Vernor', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2018-09-21 09:35:17', 13);
insert into notes (id, note_name, content, date_created, folder_id) values (85, 'Wain', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2019-02-15 14:32:54', 13);
insert into notes (id, note_name, content, date_created, folder_id) values (86, 'Maurine', 'Donec semper sapien a libero. Nam dui.', '2019-01-03 05:14:01', 10);
insert into notes (id, note_name, content, date_created, folder_id) values (87, 'Dawna', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2018-11-28 15:20:03', 3);
insert into notes (id, note_name, content, date_created, folder_id) values (88, 'Reggi', 'Nam dui.', '2018-05-22 21:12:10', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (89, 'Karoly', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2019-01-01 04:06:49', 6);
insert into notes (id, note_name, content, date_created, folder_id) values (90, 'Shannon', 'In congue. Etiam justo.', '2019-04-03 19:43:05', 17);
insert into notes (id, note_name, content, date_created, folder_id) values (91, 'Antone', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', '2018-03-27 13:19:04', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (92, 'Bobette', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-11-23 21:42:29', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (93, 'Kora', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2018-12-15 00:21:05', 9);
insert into notes (id, note_name, content, date_created, folder_id) values (94, 'Pierette', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', '2018-03-22 05:41:08', 5);
insert into notes (id, note_name, content, date_created, folder_id) values (95, 'Danna', 'Integer non velit.', '2018-10-16 02:33:06', 16);
insert into notes (id, note_name, content, date_created, folder_id) values (96, 'Shirl', 'Sed ante. Vivamus tortor.', '2018-11-04 01:25:37', 15);
insert into notes (id, note_name, content, date_created, folder_id) values (97, 'Gilligan', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2019-03-11 08:34:09', 14);
insert into notes (id, note_name, content, date_created, folder_id) values (98, 'Lammond', 'In sagittis dui vel nisl. Duis ac nibh.', '2018-03-23 16:34:48', 8);
insert into notes (id, note_name, content, date_created, folder_id) values (99, 'Bordy', 'Phasellus sit amet erat.', '2019-02-14 10:14:28', 1);
insert into notes (id, note_name, content, date_created, folder_id) values (100, 'Doralyn', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2018-04-29 10:21:47', 11);


COMMIT;